// samples/othello-vue/src/App.vue
<template>
  <div>
    <div class="controls">
      <select v-model="selectedType" @change="onOthelloTypeChange">
        <option v-for="type in gameRules.values()" :key="type.descript" :value="type.descript">
          {{ type.descript }}
        </option>
      </select>
      <input
        v-if="selectedType === gameRules.getDefaultCustomType().descript"
        type="number"
        :value="gameAction.information.getType().cols"
        @input="onCustomSizeChange"
        :min="gameRules.minSize"
        placeholder="Board Size"
      />
    </div>
    <div class="board-description">
      <p>Board Size: {{ getBoardSizeDescription(gameAction) }}</p>
      <label>
        Simulation Placement:
        <input type="checkbox" v-model="customPlacement" @change="onCustomPlacementChange" />
      </label>
      <select v-if="customPlacement" v-model="selectedPiece" @change="onPieceSelectionChange">
        <option value="black">Black</option>
        <option value="white">White</option>
      </select>
    </div>
    <div class="board" :style="gridTemplateStyle">
      <div v-for="(row, rowIndex) in board" :key="rowIndex" class="row">
        <div
          v-for="(cell, colIndex) in row"
          :key="colIndex"
          :class="getCellClassName(cell)"
          @click="onCellClick(rowIndex, colIndex)"
        ></div>
      </div>
    </div>
    <div class="info">
      <p>Current Player: {{ gameAction.information.getCurrentPlayer() }}</p>
      <p>Black: {{ counts.black }}</p>
      <p>White: {{ counts.white }}</p>
    </div>
    <button @click="onReset">Reset</button>
  </div>
</template>

<script>
import { Piece, Player } from '../../src/othello_core';
import { OthelloError, OthelloGame } from '../../src/othello_framework';

export default {
  data() {
    const onError = (error) => {
      alert(`Error: ${OthelloError[error]}`);
    };

    const onGameOver = (winner) => {
      if (winner == null) {
        alert("Game Over! Both sides draw");
        return;
      }
      let winner_str = winner === Player.BLACK_PLAYER ? "Black" : "White";
      alert(`Game Over! Winner: ${winner_str}`);
    };

    const onBoardChange = (counts, board) => {
      this.board = [...board];
      this.counts = counts;
    };

    const onRestarted = () => {
      this.customPlacement = false;
    };

    const game = new OthelloGame(onRestarted, onError, onGameOver, onBoardChange);
    const gameRules = game.rules;
    const gameAction = game.action;

    return {
      game,
      gameRules,
      gameAction,
      board: gameAction.information.getBoard(),
      counts: gameAction.information.getPieceCounts(),
      selectedType: gameAction.information.getType().descript,
      customPlacement: false,
      selectedPiece: Piece.BLACK,
    };
  },
  methods: {
    onCellClick(row, col) {
      this.gameAction.putPiece(row, col);
    },
    onReset() {
      this.gameAction.resetGame();
    },
    onOthelloTypeChange(event) {
      const selectedDescription = event.target.value;
      const selectedType = this.gameRules.values().find(
        (type) => type.descript === selectedDescription
      ) || this.gameRules.getDefaultCustomType();

      this.selectedType = selectedType.descript;
      this.gameAction.setType(selectedType);
    },
    onCustomSizeChange(event) {
      const size = parseInt(event.target.value, 10);
      this.gameAction.setType(this.gameRules.createCustomOthelloType(size));
    },
    getBoardSizeDescription(gameAction) {
      const type = gameAction.information.getType();
      return `${type.rows} x ${type.cols}`;
    },
    getCellClassName(cell) {
      return `cell ${cell === Piece.BLACK ? 'black' : cell === Piece.WHITE ? 'white' : ''}`;
    },
    onCustomPlacementChange(event) {
      let isSelected = event.target.checked;
      this.customPlacement = isSelected;
      this.gameAction.customerBoard.setCustomBoard(isSelected);
    },
    onPieceSelectionChange(event) {
      this.selectedPiece = event.target.value === 'black' ? Piece.BLACK : Piece.WHITE;
      let player = event.target.value === 'black' ? Player.BLACK_PLAYER : Player.WHITE_PLAYER;
      this.gameAction.customerBoard.setCurrentPlayer(player);
    },
  },
  computed: {
    gridTemplateStyle() {
      return {
        gridTemplateRows: `repeat(${this.board.length}, 1fr)`,
        gridTemplateColumns: `repeat(${this.board[0].length}, 1fr)`,
      };
    },
  },
};
</script>

<style>

</style>

// src/App.tsx
import React, { useEffect, useState } from 'react';
import './App.css';
import {
  Piece,
  Player, 
  PieceCounts,
  IOthelloRule,
} from './othello_core';

import {  
  OthelloError, 
  OthelloGame,
  IOthelloAction,
} from './othello_framework';


const App: React.FC = () => {

    const onError = (error: OthelloError) => {
        alert(`Error: ${OthelloError[error]}`);
    };

    const onGameOver = (winner: Player | null) => {
        if(winner == null) {
            alert("Game Over! Both sides draw");
            return;
        }
        let winner_str = winner === Player.BLACK_PLAYER ? "Block" : "White";
        alert(`Game Over! Winner: ${winner_str}`);
    };

    const onBoardChange = (counts: PieceCounts, board: (Piece | null)[][]) => {
        updateBoard([...board]);
        updateCounts(counts);
    };

    const onRestarted = () => {
        setCustomPlacement(false);
    }

    const [game] = useState<OthelloGame>(new OthelloGame(onRestarted, onError, onGameOver, onBoardChange));
    const [gameRules] = useState<IOthelloRule>(game.rules);
    const [gameAction] = useState<IOthelloAction>(game.action);
    const [board, updateBoard] = useState<(Piece | null)[][]>(gameAction.information.getBoard());
    const [counts, updateCounts] = useState<PieceCounts>(gameAction.information.getPieceCounts);
    const [selectedType, setSelectedType] = useState<string>(gameAction.information.getType().descript);

    const [customPlacement, setCustomPlacement] = useState<boolean>(false);
    const [selectedPiece, setSelectedPiece] = useState<Piece>(Piece.BLACK);

    useEffect(() => {
        gameAction.resetGame();
    }, [gameAction]);


    const onCellClick = (row: number, col: number) => {
        gameAction.putPiece(row, col);
    };

    const onReset = () => {
        gameAction.resetGame();
    };

    const onOthelloTypeChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
        const selectedDescription = event.target.value;
        const selectedType = gameRules.values().find(
            type => type.descript === selectedDescription) || gameRules.getDefaultCustomType();

        setSelectedType(selectedType.descript);

        gameAction.setType(selectedType);
    };
  

    const onCustomSizeChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        const size = parseInt(event.target.value, 10);

        gameAction.setType(gameRules.createCustomOthelloType(size));
    };
  

    const getBoardSizeDescription = (gameAction: IOthelloAction) => {
        const type = gameAction.information.getType();
        return `${type.rows} x ${type.cols}`;
    };

    const getCellClassName = (cell: Piece | null) => {
        return `cell ${cell === Piece.BLACK ? 'black' : cell === Piece.WHITE ? 'white' : ''}`;
    };

    const gridTemplateStyle = {
        gridTemplateRows: `repeat(${board.length}, 1fr)`,
        gridTemplateColumns: `repeat(${board[0].length}, 1fr)`
    };

    const onCustomPlacementChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        let isSelected = event.target.checked;
        setCustomPlacement(isSelected);

        gameAction.customerBoard.setCustomBoard(isSelected);
    };

    const onPieceSelectionChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
        setSelectedPiece(event.target.value === 'black' ? Piece.BLACK : Piece.WHITE);

        let plyer = event.target.value === 'black' ? Player.BLACK_PLAYER : Player.WHITE_PLAYER;

        gameAction.customerBoard.setCurrentPlayer(plyer);
    };

  return (
    <div>
        <div className="controls">
            <select onChange={onOthelloTypeChange} value={selectedType}>
                {gameRules.values().map((type) => (
                    <option key={type.descript} value={type.descript}>
                        {type.descript}
                    </option>
                ))}
            </select>
            {selectedType === gameRules.getDefaultCustomType().descript && (
                <input
                    type="number"
                    value={gameAction.information.getType().cols}
                    onChange={onCustomSizeChange}
                    min={gameRules.minSize}
                    placeholder="Board Size"
                />
            )}
        </div>
        <div className="board-description">
            <p>Board Size: {getBoardSizeDescription(gameAction)}</p>
            <label>
                Simulation Placement:
                <input
                    type="checkbox"
                    checked={customPlacement}
                    onChange={onCustomPlacementChange}
                />
            </label>
            {customPlacement && (
                <select onChange={onPieceSelectionChange} value={selectedPiece === Piece.BLACK ? 'black' : 'white'}>
                    <option value="black">Black</option>
                    <option value="white">White</option>
                </select>
            )}
        </div>
        <div className="board" style={gridTemplateStyle}>
            {board.map((row, rowIndex) => (
                <div key={rowIndex} className="row">
                    {row.map((cell, colIndex) => (
                        <div
                            key={colIndex}
                            className={getCellClassName(cell)}
                            onClick={() => onCellClick(rowIndex, colIndex)}
                        >
                        </div>
                    ))}
                </div>
            ))}
        </div>
        <div className="info">
            <p>Current Player: {gameAction.information.getCurrentPlayer()}</p>
            <p>Black: {counts.black}</p>
            <p>White: {counts.white}</p>
        </div>
        <button onClick={onReset}>Reset</button>
    </div>
  );
};

export default App;
